# Generated by Django 6.0 on 2026-01-04 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_class', models.IntegerField(verbose_name='Номер класса')),
                ('letter_class', models.CharField(max_length=1, verbose_name='Буква класса')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('classes', models.ManyToManyField(blank=True, related_name='SchoolClass', to='school_app.schoolclass', verbose_name='Классы, в которых преподается')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True, verbose_name='ID учителя')),
                ('password', models.CharField(blank=True, editable=False, max_length=6, null=True, verbose_name='Пароль для входа')),
                ('classes', models.ManyToManyField(related_name='teachers', to='school_app.schoolclass', verbose_name='Классы')),
                ('subjects', models.ManyToManyField(related_name='teachers', to='school_app.subject', verbose_name='Предметы')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
    ]
